export const projects = [
    {
        id: 1,
        title: 'Netflix Clone',
        image: '/netflixHome.PNG',
        description: 'This project done using React, Redux for state management, Firebase for authentication and hosting. I have used TMDB API to retrieve the movies and to display them in my application. Also created a profile page for the user who logged into the application can view that.',
        repoLink: 'https://github.com/Sai1916/Netflix-Clone',
        demoLink: 'https://netflix-clone-27942.web.app/',
    },
    {
        id: 2,
        title: 'Disney+ Clone',
        image: '/Home.png',
        description: 'This project done using React, Redux for state management, Firebase for authentication, storage and for hosting.I have used TMDB API for retrieving movies and stored then in my firebase firestore and getting back data from firestore into my application.',
        repoLink: 'https://github.com/Sai1916/disney_clone',
        demoLink: 'https://disney-clone-76a2f.web.app/',
    },
    {
        id: 3,
        title: 'BookMyShow App Redesign',
        image: '/bookmyshow2.png',
        description: 'The BookMyShow App redesign has done using Adobe-XD with both Light-mode and Dark-mode.',
        repoLink: '',
        demoLink: 'https://xd.adobe.com/view/f65cd26e-a455-4c4c-ade7-af014605a4c1-a30f/',
    },
    {
        id: 4,
        title: 'Youtube Homepage Frontend',
        image: '/Youtube.png',
        description: 'The Youtube Homepage frontend development was done using React.js and I have used Material-UI Library for the icons.',
        repoLink: '',
        demoLink: 'https://youtube-clone-frontend.netlify.app',
    },
    {
        id: 5,
        title: 'Netflix Clone App',
        image: '/netflix-react-native.jpg',
        description: 'This app was developed using react-native with expo, I have used firebase for authentication and database. I used TMDB API to get movie data and displayed them in my app, also added a detail screen to render specific movie details if we click on any movie poster.',
        repoLink: 'https://github.com/Sai1916/Netflix-Clone-React-Native',
        demoLink: 'https://expo.dev/@sumedh_expo/netflix-clone-app',
    },
    {
        id: 6,
        title: 'Uber-Eats-Clone React-Native',
        image: '/uber-eats.jpg',
        description: 'The uber-eats-clone was developed using react-native with expo and used Yelp API to get dynamic restaurant data, also used navigation in this application.',
        repoLink: 'https://github.com/Sai1916/uber-eats-clone',
        demoLink: 'https://expo.dev/@sumedh_expo/uber-eats-clone',
    },
    {
        id: 7,
        title: 'Hospital Appointment Booking App',
        image: '/hapb.png',
        description: 'This App was designed using React-Native and used Expo for creating a react-native project. This app contains 3 tabs which has HomeScreen, Appointment Scheduling Screen and Profile Screen.',
        repoLink: 'https://github.com/Sai1916/Hospital-Appointment-Booking-App',
        demoLink: 'https://expo.dev/@sumedh_expo/hospitalappointmentbooking',
    },
    {
        id: 8,
        title: 'Todo App using React-Native',
        image: '/todo.png',
        description: 'This App was designed using React-Native and used Expo for creating a react-native project. This app contains 2 screens which has HomeScreen and Add-Todo Screen.',
        repoLink: 'https://github.com/Sai1916/TodoApp-ReactNative-and-TailwindCss',
        demoLink: 'https://expo.dev/@sumedh_expo/TaskSaver',
    },
    {
        id: 9,
        title: 'Medium Clone using Next.js and Sanity.io',
        image: '/medium-pic.png',
        description: 'This App was designed using Next.js and Sanity.io for Content Management System. This app is nothing but a blog site which is similar to Medium.',
        repoLink: 'https://github.com/Sai1916/medium-nextjs-sanity-clone',
        demoLink: 'https://sumedhblogs.vercel.app/',
    }
]
