import Head from 'next/head'
import About from '../src/components/About'
import Header from '../src/components/Header'
import styles from '../styles/Home.module.css'
import Skills from '../src/components/Skills'
import Education from '../src/components/Education'
import Projects from '../src/components/Projects'

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/FortAwesome/Font-Awesome@5.13.0/css/all.min.css" />
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo1.jpg" />
      </Head>
      
      <Header />
      <About />
      <Skills />
      <Education />
      <Projects />
    </div>
  )
}
